#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 sseutils32.nasm; fi;
nasm -f elf32 ./asm/baricentro_input.nasm;
gcc -w -m32 -msse -O0 -no-pie sseutils32.o ./asm/baricentro_input.o fss32c_no_padding.c -o fss32c_no_padding -lm;
pars="-c ../../data/coeff32_8.ds2 -r ../../data/rand32_8_64_250.ds2 -x ../../data/x32_8_64.ds2 -np 64 -si 0.1 -sv 0.0125 -w 1.25 -it 250 -d";
# for arg; do pars=$pars" "$arg; done;
echo $pars;
./fss32c_no_padding $pars
