#!/bin/bash
for f in $(ls ./*32.nasm); do
	nasm -f elf32 $f;
done;
gcc -w -m32 -msse -O0 -no-pie ./*32.o fss32c.c -o fss32c -lm;
pars="-c ../../data/coeff32_8.ds2 -r ../../data/rand32_8_64_250.ds2 -x ../../data/x32_8_64.ds2 -np 64 -si 0.1 -sv 0.0125 -w 1.25 -it $1 -d";
# for arg; do pars=$pars" "$arg; done;
echo $pars;
./fss32c $pars
