#!/bin/bash
for f in $(ls ./*32.nasm); do
	nasm -f elf32 $f;
done;
gcc -w -m32 -msse -O0 -no-pie ./*32.o fss32c.c -o fss32c -lm;
pars="-c ../../data/coeff32_9.ds2 -r ../../data/rand32_9_21_250.ds2 -x ../../data/x32_9_21.ds2 -np 21 -si 0.3 -sv 0.0325 -w 3.25 -it $1 -d";
# for arg; do pars=$pars" "$arg; done;
echo $pars;
./fss32c $pars
