#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 sseutils32.nasm; fi;
for f in $(ls ./asm/*32.nasm); do
	nasm -f elf32 $f;
done;
gcc -w -m32 -msse -O0 -no-pie sseutils32.o ./asm/*32.o fss32c_padding.c -o fss32c_padding -lm;
pars="-c ../../data/coeff32_256.ds2 -r ../../data/rand32_256_768_1250.ds2 -x ../../data/x32_256_768.ds2 -np 768 -si 0.003 -sv 0.0004 -w 0.04 -it 1250 -d";
# for arg; do pars=$pars" "$arg; done;
echo $pars;
./fss32c_padding $pars
