#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 sseutils32.nasm; fi;
nasm -f elf32 ./asm/baricentro_input_padding.nasm;
gcc -w -m32 -msse -O0 -no-pie sseutils32.o ./asm/baricentro_input_padding.o fss32c_padding.c -o fss32c_padding -lm;
pars="-c ../../data/coeff32_11.ds2 -r ../../data/rand32_11_10_250.ds2 -x ../../data/x32_11_10.ds2 -np 10 -si 2 -sv 0.2 -w 20 -it 1 -d";
# for arg; do pars=$pars" "$arg; done;
echo $pars;
./fss32c_padding $pars
