#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 sseutils32.nasm; fi;
nasm -f elf32 ./test_baricentro_input.nasm;
gcc -w -m32 -msse -O0 -no-pie sseutils32.o ./test_baricentro_input.o test_fss32c.c -o test_fss32c -lm;
pars="-c ../data/coeff32_8.ds2 -x ../data/x32_8_64.ds2 -np 64 -si 1 -sv 0.1 -w 1.25 -it $1 -a $2 -d";
# for arg; do pars=$pars" "$arg; done;
echo $pars;
./test_fss32c $pars
